# 07_logging_monitoring/log-aggregation/filebeat.yml

filebeat.inputs:
  # Docker container logs
  - type: container
    enabled: true
    paths:
      - "/var/lib/docker/containers/*/*.log"

    # Decode JSON logs
    json.message_key: log
    json.keys_under_root: true
    json.add_error_key: true

    # Add container metadata
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - add_labels:
          labels:
            logtype: "docker"
            environment: "development"

  # Application log files
  - type: log
    enabled: true
    paths:
      - /var/log/app/*.log
      - /var/log/app/*/*.log

    fields:
      logtype: "application"
      service: "demo-app"
    fields_under_root: true

    # Multiline pattern for stack traces
    multiline.pattern: '^\s'
    multiline.negate: false
    multiline.match: after

    # JSON parsing
    json.keys_under_root: true
    json.overwrite_keys: true

  # System logs
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/messages
      - /var/log/auth.log

    fields:
      logtype: "system"
    fields_under_root: true

  # Nginx access logs
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log

    fields:
      logtype: "nginx-access"
      service: "nginx"
    fields_under_root: true

  # Nginx error logs
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/error.log

    fields:
      logtype: "nginx-error"
      service: "nginx"
    fields_under_root: true

    # Multiline for nginx error messages
    multiline.pattern: '^\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}'
    multiline.negate: true
    multiline.match: after

# Global processors
processors:
  # Add host information
  - add_host_metadata:
      when.not.contains.tags: forwarded

  # Add process metadata
  - add_process_metadata:
      match_pids: ["process.pid"]
      include_fields: ["process.name"]

  # Add timestamp
  - timestamp:
      field: "@timestamp"
      layouts:
        - "2006-01-02T15:04:05.000Z"
        - "2006-01-02T15:04:05Z"
      test:
        - "2023-05-15T14:30:45.123Z"
        - "2023-05-15T14:30:45Z"

  # Drop empty events
  - drop_event:
      when:
        equals:
          message: ""

  # Rename fields
  - rename:
      fields:
        - from: "container.name"
          to: "container_name"
        - from: "container.image.name"
          to: "container_image"

  # Add environment labels
  - add_labels:
      labels:
        environment: "${ENVIRONMENT:development}"
        cluster: "${CLUSTER_NAME:local}"

# Output configuration
output.logstash:
  hosts: ["logstash:5044"]

  # Load balancing
  loadbalance: true
  worker: 1

  # Bulk settings
  bulk_max_size: 1024

  # Compression
  compression_level: 3
  escape_html: false

# Alternative output to Elasticsearch
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "filebeat-%{+yyyy.MM.dd}"
#   template.enabled: true
#   template.pattern: "filebeat-*"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat-monitoring"

# Setup
setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

# ILM Policy
setup.ilm.enabled: auto
setup.ilm.rollover_alias: "filebeat"
setup.ilm.pattern: "{now/d}-000001"
setup.ilm.policy: "filebeat-policy"
