# 07_logging_monitoring/monitoring-stack/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "docker-monitoring"
    cluster: "development"

rule_files:
  - "/etc/prometheus/rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 5s
    metrics_path: /metrics

  # Sample application metrics
  - job_name: "sample-app"
    static_configs:
      - targets: ["sample-app:8080"]
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker daemon metrics (if enabled)
  - job_name: "docker-daemon"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 30s
    metrics_path: /metrics

  # AlertManager metrics
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]
    scrape_interval: 30s

  # Service discovery for dynamic container monitoring
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_docker_container_label_prometheus_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}
      - source_labels: [__meta_docker_container_label_prometheus_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__meta_docker_container_name]
        action: replace
        target_label: container_name
      - source_labels:
          [__meta_docker_container_label_com_docker_compose_service]
        action: replace
        target_label: service_name

  # Blackbox exporter for endpoint monitoring
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://sample-app:8080/health
          - http://sample-app:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "http://remote-storage:9201/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# Remote read configuration (optional)
# remote_read:
#   - url: "http://remote-storage:9201/api/v1/read"
