# File Location: labs/lab_05_microservices_demo/monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "microservices-demo"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:80"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:5000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["user-db:5432", "order-db:5432"]
    scrape_interval: 60s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 60s

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15672"]
    metrics_path: "/api/metrics"
    scrape_interval: 60s
