# Location: labs/lab_06_production_deployment/monitoring/production-metrics.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "production"
    environment: "prod"

rule_files:
  - "/etc/prometheus/rules/alerting.yml"
  - "/etc/prometheus/rules/recording.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s
    metrics_path: /metrics

  # NGINX metrics
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:9113"]
    scrape_interval: 15s
    metrics_path: /metrics

  # User Service metrics
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:9090"]
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: user-service

  # Order Service metrics
  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:9091"]
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: order-service

  # Notification Service metrics
  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:9092"]
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: notification-service

  # PostgreSQL metrics
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s
    metrics_path: /metrics

  # MongoDB metrics
  - job_name: "mongodb-exporter"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Kafka metrics
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Elasticsearch metrics
  - job_name: "elasticsearch-exporter"
    static_configs:
      - targets: ["elasticsearch-exporter:9114"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Blackbox exporter for endpoint monitoring
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://your-domain.com/health
          - https://your-domain.com/api/v1/users/health
          - https://your-domain.com/api/v1/orders/health
          - https://your-domain.com/api/v1/notifications/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL certificate monitoring
  - job_name: "blackbox-ssl"
    metrics_path: /probe
    params:
      module: [tls_connect]
    static_configs:
      - targets:
          - your-domain.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # DNS monitoring
  - job_name: "blackbox-dns"
    metrics_path: /probe
    params:
      module: [dns_soa]
    static_configs:
      - targets:
          - your-domain.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Grafana metrics
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: /metrics
    scrape_interval: 30s

  # Custom business metrics
  - job_name: "business-metrics"
    static_configs:
      - targets: ["business-metrics-exporter:9200"]
    scrape_interval: 60s
    metrics_path: /metrics

  # Jaeger metrics
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:16686"]
    metrics_path: /metrics
    scrape_interval: 30s

  # Docker daemon metrics
  - job_name: "docker-daemon"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 30s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      path_prefix: /
      scheme: http

remote_write:
  - url: "${REMOTE_WRITE_URL:-}"
    basic_auth:
      username: "${REMOTE_WRITE_USERNAME:-}"
      password: "${REMOTE_WRITE_PASSWORD:-}"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: "up|probe_success|http_requests_total|http_request_duration_seconds.*|cpu_usage_percent|memory_usage_percent|disk_usage_percent"
        action: keep

remote_read:
  - url: "${REMOTE_READ_URL:-}"
    basic_auth:
      username: "${REMOTE_READ_USERNAME:-}"
      password: "${REMOTE_READ_PASSWORD:-}"
